export const smartContract = {
  address: "0x80f54dfecc052e2103ade4d018a4857539ab8f57",
  abi: [
    { inputs: [], stateMutability: "nonpayable", type: "constructor" },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: "uint256",
          name: "id",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "quantityReceived",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "string",
          name: "area",
          type: "string",
        },
      ],
      name: "InputOutputRecorded",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: "uint256",
          name: "id",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "quantityDisposed",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "string",
          name: "area",
          type: "string",
        },
        {
          indexed: false,
          internalType: "string",
          name: "landfillSite",
          type: "string",
        },
      ],
      name: "LandfillEntryRecorded",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: "uint256",
          name: "id",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "address",
          name: "districtAdmin",
          type: "address",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "totalAmount",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "string",
          name: "area",
          type: "string",
        },
      ],
      name: "WasteCollectionRecorded",
      type: "event",
    },
    {
      inputs: [
        { internalType: "address", name: "_user", type: "address" },
        {
          internalType: "enum WasteManagementSystem.UserRole",
          name: "_role",
          type: "uint8",
        },
      ],
      name: "assignUserRole",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      name: "districtAdminReports",
      outputs: [
        { internalType: "uint256", name: "id", type: "uint256" },
        { internalType: "address", name: "admin", type: "address" },
        { internalType: "string", name: "ipfsHash", type: "string" },
        { internalType: "uint256", name: "date", type: "uint256" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "_id", type: "uint256" }],
      name: "getDistrictAdminReport",
      outputs: [
        {
          components: [
            { internalType: "uint256", name: "id", type: "uint256" },
            { internalType: "address", name: "admin", type: "address" },
            { internalType: "string", name: "ipfsHash", type: "string" },
            { internalType: "uint256", name: "date", type: "uint256" },
          ],
          internalType: "struct WasteManagementSystem.WeeklyReport",
          name: "",
          type: "tuple",
        },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "_id", type: "uint256" }],
      name: "getInputOutputEntry",
      outputs: [
        {
          components: [
            { internalType: "uint256", name: "id", type: "uint256" },
            { internalType: "uint256", name: "inputDate", type: "uint256" },
            { internalType: "uint256", name: "outputDate", type: "uint256" },
            {
              internalType: "uint256",
              name: "quantityReceived",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "recyclablePercentage",
              type: "uint256",
            },
            { internalType: "string", name: "area", type: "string" },
          ],
          internalType: "struct WasteManagementSystem.InputOutputEntry",
          name: "",
          type: "tuple",
        },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "_id", type: "uint256" }],
      name: "getLandfillAdminReport",
      outputs: [
        {
          components: [
            { internalType: "uint256", name: "id", type: "uint256" },
            { internalType: "address", name: "admin", type: "address" },
            { internalType: "string", name: "ipfsHash", type: "string" },
            { internalType: "uint256", name: "date", type: "uint256" },
          ],
          internalType: "struct WasteManagementSystem.WeeklyReport",
          name: "",
          type: "tuple",
        },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "_id", type: "uint256" }],
      name: "getLandfillEntry",
      outputs: [
        {
          components: [
            { internalType: "uint256", name: "id", type: "uint256" },
            { internalType: "uint256", name: "date", type: "uint256" },
            {
              internalType: "uint256",
              name: "quantityDisposed",
              type: "uint256",
            },
            { internalType: "string", name: "area", type: "string" },
            { internalType: "string", name: "landfillSite", type: "string" },
          ],
          internalType: "struct WasteManagementSystem.LandfillEntry",
          name: "",
          type: "tuple",
        },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "_id", type: "uint256" }],
      name: "getRecyclablePointAdminReport",
      outputs: [
        {
          components: [
            { internalType: "uint256", name: "id", type: "uint256" },
            { internalType: "address", name: "admin", type: "address" },
            { internalType: "string", name: "ipfsHash", type: "string" },
            { internalType: "uint256", name: "date", type: "uint256" },
          ],
          internalType: "struct WasteManagementSystem.WeeklyReport",
          name: "",
          type: "tuple",
        },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "_id", type: "uint256" }],
      name: "getWasteCollectionEntry",
      outputs: [
        {
          components: [
            { internalType: "uint256", name: "id", type: "uint256" },
            { internalType: "address", name: "districtAdmin", type: "address" },
            { internalType: "uint256", name: "date", type: "uint256" },
            { internalType: "uint256", name: "totalAmount", type: "uint256" },
            { internalType: "string", name: "area", type: "string" },
            { internalType: "string", name: "notes", type: "string" },
          ],
          internalType: "struct WasteManagementSystem.WasteCollectionEntry",
          name: "",
          type: "tuple",
        },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      name: "inputOutputEntries",
      outputs: [
        { internalType: "uint256", name: "id", type: "uint256" },
        { internalType: "uint256", name: "inputDate", type: "uint256" },
        { internalType: "uint256", name: "outputDate", type: "uint256" },
        { internalType: "uint256", name: "quantityReceived", type: "uint256" },
        {
          internalType: "uint256",
          name: "recyclablePercentage",
          type: "uint256",
        },
        { internalType: "string", name: "area", type: "string" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      name: "landfillAdminReports",
      outputs: [
        { internalType: "uint256", name: "id", type: "uint256" },
        { internalType: "address", name: "admin", type: "address" },
        { internalType: "string", name: "ipfsHash", type: "string" },
        { internalType: "uint256", name: "date", type: "uint256" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      name: "landfillEntries",
      outputs: [
        { internalType: "uint256", name: "id", type: "uint256" },
        { internalType: "uint256", name: "date", type: "uint256" },
        { internalType: "uint256", name: "quantityDisposed", type: "uint256" },
        { internalType: "string", name: "area", type: "string" },
        { internalType: "string", name: "landfillSite", type: "string" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "owner",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_inputDate", type: "uint256" },
        { internalType: "uint256", name: "_outputDate", type: "uint256" },
        { internalType: "uint256", name: "_quantityReceived", type: "uint256" },
        {
          internalType: "uint256",
          name: "_recyclablePercentage",
          type: "uint256",
        },
        { internalType: "string", name: "_area", type: "string" },
      ],
      name: "recordInputOutput",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_date", type: "uint256" },
        { internalType: "uint256", name: "_quantityDisposed", type: "uint256" },
        { internalType: "string", name: "_area", type: "string" },
        { internalType: "string", name: "_landfillSite", type: "string" },
      ],
      name: "recordLandfillEntry",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_date", type: "uint256" },
        { internalType: "uint256", name: "_totalAmount", type: "uint256" },
        { internalType: "string", name: "_area", type: "string" },
        { internalType: "string", name: "_notes", type: "string" },
      ],
      name: "recordWasteCollection",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      name: "recyclablePointAdminReports",
      outputs: [
        { internalType: "uint256", name: "id", type: "uint256" },
        { internalType: "address", name: "admin", type: "address" },
        { internalType: "string", name: "ipfsHash", type: "string" },
        { internalType: "uint256", name: "date", type: "uint256" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_id", type: "uint256" },
        { internalType: "uint256", name: "_totalAmount", type: "uint256" },
        { internalType: "string", name: "_notes", type: "string" },
      ],
      name: "updateWasteCollectionEntry",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "", type: "address" }],
      name: "userRoles",
      outputs: [
        {
          internalType: "enum WasteManagementSystem.UserRole",
          name: "",
          type: "uint8",
        },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      name: "wasteCollectionEntries",
      outputs: [
        { internalType: "uint256", name: "id", type: "uint256" },
        { internalType: "address", name: "districtAdmin", type: "address" },
        { internalType: "uint256", name: "date", type: "uint256" },
        { internalType: "uint256", name: "totalAmount", type: "uint256" },
        { internalType: "string", name: "area", type: "string" },
        { internalType: "string", name: "notes", type: "string" },
      ],
      stateMutability: "view",
      type: "function",
    },
  ],
};
