import { Inter } from 'next/font/google'
import LayoutWrapper from './LayoutWrapper'
import Header from '@/components/Shared/Header'
import Footer from '@/components/Shared/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LayoutWrapper>
          <Header />
          {children}
          <Footer />
        </LayoutWrapper>
      </body>
    </html>
  )
}
